### ISSUE TITLE
Course Location not working properly

### ISSUE THREAD

**Issue by feefles** [pennlabs/penn-mobile-ios#106]
Locations for courses always show "no location available". 

I made a comment in https://github.com/pennlabs/penn-mobile-ios/commit/9577d6454511c454a80e08d81deb7cece3cf0138
I think it was a typo. 

edit: actually I don't know, since roomBum is everywhere... but would be really nifty to have working! It's a feature I rely on :)

**Comment by dlakata** [comment]
Thanks for reporting this!
