### ISSUE TITLE
Keep radio switches consistent between Laundry and Courses

### ISSUE THREAD

**Issue by sachabest** [pennlabs/penn-mobile-ios#119]
See screenshots - Courses looks better IMO

![image](https://cloud.githubusercontent.com/assets/5625401/14768081/6f34d454-0a05-11e6-84c3-c8b1f1ad0dbc.png)

![image](https://cloud.githubusercontent.com/assets/5625401/14768082/75eb6132-0a05-11e6-94b9-c857b794e008.png)

**Comment by kbharathala** [comment]
Switching Laundry to courses style soon
