### ISSUE TITLE
Make home cell loading more efficient

### ISSUE THREAD

**Issue by DominicHolmes** [pennlabs/penn-mobile-ios#162]
lazy loading for cells that have images should be added. also we should look at more efficient ways to manage the loading of new cells on the home page as mentioned by @joshdoman

**Comment by joshdoman** [comment]
Images are already loaded asynchronously so that is not a problem. We do, however, need to figure out how to enable smooth scrolling for more complicated UI

**Comment by DominicHolmes** [comment]
Closing this until we know this is a problem. Seems fine on all newer builds.
