### ISSUE TITLE
Nav Bar labels don't update properly

### ISSUE THREAD

**Issue by DominicHolmes** [pennlabs/penn-mobile-ios#192]
You can see this my going to the More Tab, and then to Fitness. The label at the top does not change.

This also happens when you tap and hold a tab bar item, and then slide your finger off. The screen will update, but not the nav bar.

**Comment by joshdoman** [comment]
This was sort of resolved in update 4.0 but not really. @sanieldalib could you take a look? It correctly changes the label to Laundry the first time but the second it changes it to More.

**Comment by DominicHolmes** [comment]
Resolved
