### ISSUE TITLE
Laundry data doesn't load for newly added rooms

### ISSUE THREAD

**Issue by joshdoman** [pennlabs/penn-mobile-ios#270]
It doesn't appear that a new API request is made when a new laundry room is added to the laundry page. As a result, the page is blank (see below). @henrYoda Could you look into this?
![image](https://user-images.githubusercontent.com/22065307/71044284-42f01100-20ff-11ea-9154-7c8dce6b4d68.png)

**Comment by henrYoda** [comment]
I'll look into it!

**Comment by joshdoman** [comment]
Resolved.
