### ISSUE TITLE
Login behavior is different on Login screen vs More tab

### ISSUE THREAD

**Issue by DominicHolmes** [pennlabs/penn-mobile-ios#283]
When logging in from the Login screen (presented at launch), everything seems correct. Closing and reopening the app will auto-log you back in, as expected.

However logging in by pressing the "Login" button on the More tab (while in Guest mode) doesn't work in the same way. Closing and reopening the app after logging in from there will present you with the Login screen, as if you'd never logged in.

**Comment by joshdoman** [comment]
Resolved. The last login flag wasn't being saved in the More tab, which was causing the app to require login.

**Comment by joshdoman** [comment]
Resolved. The last login flag wasn't being saved in the More tab, which was causing the app to require login.
