### ISSUE TITLE
Integrate a SwiftUI privacy request screen

### ISSUE THREAD

**Issue by DominicHolmes** [pennlabs/penn-mobile-ios#284]
Use UIHostingController (https://sarunw.com/posts/swiftui-in-uikit/) to integrate a SwiftUI-based privacy / notification request screen.

The SwiftUI side of this is already built out:
<img width="929" alt="Screen Shot 2019-12-30 at 10 54 34 PM" src="https://user-images.githubusercontent.com/12633255/71612766-5b2c4b00-2b57-11ea-9f5a-3e658a2bfbb0.png">

**Comment by joshdoman** [comment]
Done!
