### ISSUE TITLE
Move info in the "Edit Your Profile" section from local storage to platform

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#327]
Currently, in the "more" tab of the app, a user can edit their profile information (name, email) but this is stored locally. When a user logs out and back in, this information is erased. Ideally, we would want to store this data in platform so when the user logs back in, their information is populated again. Requires working with platform to develop an API for us.

Currently, this information is used when making GSR Bookings and when the app refers to you on the home page (E.g. "Howdy John").

**Comment by 01jongmin** [comment]
Completed by @aantenberg 🎉
