### ISSUE TITLE
Transition group-gsr invites to use Platform API for querying users by pennkey

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#332]
Currently, we are using the study spaces API for querying users when a user tries to invite a new member. The study spaces API is unsafe (no oauth), so we should transition to using the equivalent API on platform (protected with oauth). 

We should also remove study spaces API (https://api.pennlabs.org/studyspaces/user/search?query), but this issue should be under labs-api-server.

**Comment by jonathanmelitski** [comment]
no
