### ISSUE TITLE
Remove Cocoapods Warnings

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#359]
These cocoapod warnings are annoying, and we should probable address them.

It's an easy fix, I was able to do it in a different xcode project by following some stackoverflow posts on it. 
![Screen Shot 2020-10-23 at 1 33 45 AM](https://user-images.githubusercontent.com/5091484/96975808-dccadc00-14cf-11eb-89a8-fc7455e0f462.png)

**Comment by 01jongmin** [comment]
Completed in 004522a86ca0de63cede48af1e26a690bcfad0b8
