### ISSUE TITLE
Acknowledge more contributors on the About Page

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#367]
- Change "alumni" to "recent alumni" on the about page to reflect that we do not have all alumni listed as contributors
- Add another member with the name "Other Contributors" and the PennLabs logo as the "face" under the "recent alumni" section to acknowledge that other people have contributed to the iOS app. 

- Current about page shown for reference:
![Simulator Screen Shot - iPhone 12 Pro - 2020-11-01 at 12 25 53](https://user-images.githubusercontent.com/5091484/97813598-00afbf80-1c3e-11eb-8e85-8c70b2ee16e5.png)
![Simulator Screen Shot - iPhone 12 Pro - 2020-11-01 at 12 28 54](https://user-images.githubusercontent.com/5091484/97813601-04434680-1c3e-11eb-9226-5cafdd18a1ac.png)
![Simulator Screen Shot - iPhone 12 Pro - 2020-11-01 at 12 30 06](https://user-images.githubusercontent.com/5091484/97813602-05747380-1c3e-11eb-8d45-79469f2dc678.png)

**Comment by 01jongmin** [comment]
Resolved by removing all names from the app.
