### ISSUE TITLE
Upgrade Crashlytics to not use Fabric (will be deprecated Nov. 15)

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#369]
I'm pretty sure we are using Fabric Crashlytics. There's an easy upgrade guide on how to move away from Fabric, which will soon be deprecated, onto whatever's newer. Upgrade Guide: [https://firebase.google.com/docs/crashlytics/upgrade-sdk](https://firebase.google.com/docs/crashlytics/upgrade-sdk). 
![Screen Shot 2020-11-07 at 2 54 57 PM](https://user-images.githubusercontent.com/5091484/98453007-6baf3980-2109-11eb-92cb-dc5eae9391b8.png)

**Comment by jonathanmelitski** [comment]
no.


Migrated to different analytics implementation.
