### ISSUE TITLE
UISwitch not working everywhere in app (iOS 14 bug)

### ISSUE THREAD

**Issue by raunaqsingh2020** [pennlabs/penn-mobile-ios#375]
add `cell.contentView.isUserInteractionEnabled = false` for tableView cells with switches.

**Comment by r3khaan** [comment]
- laundry page: scrolling, select a room button
- gsr page: delete gsr reservation button
- home page, click on course

**Comment by nitinseshadri** [comment]
Hi, I'm still unable to tap the switch to enable the Two-Step Code feature in Penn Mobile.

I have an iPhone 12 with iOS 14.7.1 and the latest version of Penn Mobile (6.5.5).

**Comment by 01jongmin** [comment]
@nitinseshadri Thank you for your feedback. Right now, two-step authentication is disabled due to technical challenges. We hope to enable this soon.
