### ISSUE TITLE
GSR Location names cutoff

### ISSUE THREAD

**Issue by r3khaan** [pennlabs/penn-mobile-ios#383]
![Simulator Screen Shot - iPhone 11 - 2021-03-21 at 20 13 51](https://user-images.githubusercontent.com/5091484/112009839-252d0b00-8afd-11eb-91af-3a0957f49973.png)

Perhaps we should expand the UIPickerView horizontally to include a longer part of the names, otherwise it looks jank!

**Comment by 01jongmin** [comment]
Will be resolve through the upcoming GSR redesign
