### ISSUE TITLE
revamp About view

### ISSUE THREAD

**Issue by cerenali** [pennlabs/penn-mobile-ios#46]
make it prettier

**Comment by sachabest** [comment]
Copyright needs to be updated to 2016

**Comment by kbharathala** [comment]
![simulator screen shot mar 21 2016 10 03 44 pm](https://cloud.githubusercontent.com/assets/5233069/13940086/cf630694-efb0-11e5-8ee2-42b289e690a5.png)

**Comment by sachabest** [comment]
👍👍👍

**Comment by kbharathala** [comment]
Update copyright if you haven't already.

**Comment by joshdoman** [comment]
Ok thanks! Should it be different than @ 2017 PennLabs?

**Comment by kbharathala** [comment]
Nope that's fine!
