### ISSUE TITLE
add alert to directory view for accessing pennkey-secured information

### ISSUE THREAD

**Issue by cerenali** [pennlabs/penn-mobile-ios#49]
(should probably tie in to pennkey authentication stuff)

* should be intuitive/non-intrusive

**Comment by sachabest** [comment]
@adelq is there any protected information? I thought we had that disabled?

**Comment by adelq** [comment]
nope, everything currently shown is public info. I'm not sure what this issue is for. @cerenali?

**Comment by sachabest** [comment]
I think I had a branch with that detail enabled using a PCR key we had. Killed it because it was a gaping security hole lol
