### ISSUE TITLE
Fix button target for KCECH in dining listview

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-ios#80]
Whenever I try to look at KCHECH's menu, it reacts as if I'd checked its hours (by clicking on the name, rather than the background picture). This might be because KCHECH's name spelled out is really long and is covering the area where you'd normally be able to tap to see the menu.

**Comment by sachabest** [comment]
That's the behavior when the app can't pull a menu. Not when the name is long. That means no menu is available from the API or There is some other connection issue.

**Comment by sachabest** [comment]
@adelq WNF?

**Comment by adelq** [comment]
Yes, makes sense
