### ISSUE TITLE
Laundry Machine Access

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-ios#83]
Add view for laundry machines in college housing. These can be obtained from the Penn Labs [laundry API](https://github.com/pennlabs/penn-mobile-server/blob/master/README.md#laundry)

 - [x] Add listing of college houses
 - [x] Add listing of floors with laundry within a college house
 - [x] Show indicators next to each floor within a college house for washer and dryer availability
 - [x] Ability to set notification on particular washer/dryer availability
 - [ ] Ability to set notification on when a particular load is done

Color palette for indicators with @eureika

**Comment by kbharathala** [comment]
Yay!! #113 and #110
