### ISSUE TITLE
Incorrect phone numbers on Support Page

### ISSUE THREAD

**Issue by feefles** [pennlabs/penn-mobile-ios#90]
Some of your support phone numbers are incorrect. 
SHS for sure is not right, it should be 215-746-3535

You may want to check the other ones.

**Comment by kbharathala** [comment]
already fixed by @adelq

**Comment by adelq** [comment]
Yup, already fixed but needs to be deployed. Thanks @feefles :)

**Comment by sachabest** [comment]
Yall should try triple tapping the support menu bar icon at the top of the screen.

**Comment by kbharathala** [comment]
Is that the easter egg? hahaha
