### ISSUE TITLE
Complete 2.0 Mockups

### ISSUE THREAD

**Issue by afischer** [pennlabs/penn-mobile-ios#93]

**Comment by afischer** [comment]
PROGRESS! 
![screen shot 2015-12-27 at 3 40 43 pm](https://cloud.githubusercontent.com/assets/5422397/12011912/4e413a06-acb0-11e5-8cc4-91197c179df6.png)

**Comment by afischer** [comment]
[Early designs](https://github.com/pennlabs/penn-mobile-ios/files/72793/PennMobile.Redesign.V1.pdf)
lmk if this is going in the direction you guys want.

**Comment by dlakata** [comment]
nice work!

**Comment by kbharathala** [comment]
using designs from Tiffany
